name: build-deploy
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
jobs:
  build-push:
    if: ${{ (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master') || github.event.pull_request.merged }}
    environment: production
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kartemdev/magiclist-api:latest
  pull-deploy:
    needs: build-push
    environment: production
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Connect to SSH & Execution entrypoint.sh
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_HOST: ${{secrets.APP_HOST}}
          POSTGRES_URL: ${{secrets.POSTGRES_URL}}
          ACCESS_SECRET_KEY: ${{secrets.ACCESS_SECRET_KEY}}
          GMAIL: ${{secrets.GMAIL}}
          GMAIL_CLIENT_ID: ${{secrets.GMAIL_CLIENT_ID}}
          GMAIL_CLIENT_SECRET: ${{secrets.GMAIL_CLIENT_SECRET}}
          GMAIL_REFRESH_TOKEN: ${{secrets.GMAIL_REFRESH_TOKEN}}
          ENTRYPOINT_SH: ${{secrets.ENTRYPOINT_SH}}
        with:
          envs: APP_HOST, POSTGRES_URL, ACCESS_SECRET_KEY, GMAIL, GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN, ENTRYPOINT_SH
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            chmod +x $ENTRYPOINT_SH
            $ENTRYPOINT_SH
